### PR TITLE
fix: Remove cozy-client-js copy into public path

### PR DESCRIPTION
**Pull request by cballevre**
We copy `cozy-client-js` to the public folder but not all projects have this dependency anymore. I decided to strip this part of the config because it was blocking the building of cozy-notes public assets. I tried on cozy-drive with watch and build, it seems to have no impact. But if necessary, I propose to bring this specific config back to cozy-drive.

### CODE REVIEW

**Comment by Crash--** [comment]
We had an issue on that: https://github.com/cozy/create-cozy-app/issues/1369 but I don't know why this issue is closed.

**Comment by Crash--** [comment]
I just read the code, it'll not work. We need to still copy cozy-client-js. I imagine you have tested on watch but not without being unloged on the cozy? 

We should add a new flag... again... to still support this cozy-client-js. I think we can do a breaking change: By default we do not do anything with cozy-client-js, but if the app says "I want cozy-client-js", then we handle it. OK?

**Comment by cballevre** [comment]
For sure, I will add a new option on cozy-script `--cozyClientJs` which will import cozy-client-js in public assets add also in development mode.

**Comment by cballevre** [comment]
All tests are good with this morning changes 😄 @Crash-- can I have a review ? thanks in advance

**Review by Crash-- — APPROVED** [review]

**Pull request merged**
