### PR TITLE
feat: Include cozy-client at the cozy-bar init

### PR DESCRIPTION
**Pull request by edas**
Including the local cozyClient instance when initializing the cozy-bar
will allows the bar to reuse it instead of creating its own new one.
Doing so, the app and the bar will share the same instance, and will
be able to share the same config and the same tokens.

### CODE REVIEW

**Comment by edas** [comment]
The 2 build errors are not from this PR. 

```
 ● App from cozy-scripts › should work correctly with publish --help option

    expect(received).not.toThrow()

    Error name:    "Error"

    Error message: "Something went wrong when installing the latest version of 'cozy-app-publish'"

          258 |     ))

          259 |     expect(() => {

        > 260 |       publishScript({

              |       ^

          261 |         cliArgs: ['--help']

          262 |       })

          263 |     }).not.toThrow()

          at runGlobalPackageCLI (node_modules/cozy-scripts/utils/runGlobalPackageCLI.js:31:11)

          at runCozyAppPublish (node_modules/cozy-scripts/scripts/publish.js:10:3)

          at publishScript (../../packages/cozy-scripts/test/scripts.spec.js:260:7)

          at Object.<anonymous> (../../node_modules/expect/build/toThrowMatchers.js:81:11)

          at Object.throwingMatcher [as toThrow] (../../node_modules/expect/build/index.js:342:33)

          at Object.toThrow (../../packages/cozy-scripts/test/scripts.spec.js:263:12)

      261 |         cliArgs: ['--help']

      262 |       })

    > 263 |     }).not.toThrow()

          |            ^

      264 |   })

      265 | 

      266 |   // the --help option should always be a working option of the release CLI

      at Object.toThrow (packages/cozy-scripts/test/scripts.spec.js:263:12)

  ● App from cozy-scripts › should work correctly with release --help option

    expect(received).not.toThrow()

    Error name:    "Error"

    Error message: "Something went wrong when installing the latest version of 'cozy-release'"

          275 |     ))

          276 |     expect(() => {

        > 277 |       releaseScript({

              |       ^

          278 |         cliArgs: ['--help']

          279 |       })

          280 |     }).not.toThrow()

          at runGlobalPackageCLI (node_modules/cozy-scripts/utils/runGlobalPackageCLI.js:31:11)

          at runCozyRelease (node_modules/cozy-scripts/scripts/release.js:10:3)

          at releaseScript (../../packages/cozy-scripts/test/scripts.spec.js:277:7)

          at Object.<anonymous> (../../node_modules/expect/build/toThrowMatchers.js:81:11)

          at Object.throwingMatcher [as toThrow] (../../node_modules/expect/build/index.js:342:33)

          at Object.toThrow (../../packages/cozy-scripts/test/scripts.spec.js:280:12)

      278 |         cliArgs: ['--help']

      279 |       })

    > 280 |     }).not.toThrow()

          |            ^

      281 |   })

      282 | 

      283 |   it('should return two separated configs if services config is used (also test app.config.js usage)', () => {

      at Object.toThrow (packages/cozy-scripts/test/scripts.spec.js:280:12)

```

I may investigate, but not today

**Comment by ptbrowne** [comment]
I am OK to merge as is.

**Comment by nono** [comment]
It looks like there are a lot of files in conflict. Should we close this PR?

**Comment by ptbrowne** [comment]
Yep, I don't think anyone understands what's going on here. I'm closing.

**Pull request closed without merging**
