### PR TITLE
fix: Merge locales and langs entry in manifest

### PR DESCRIPTION
**Pull request by Merkur39**
Today, in the Store, in the details of an application,
we cannot add screenshots keeping the translations
in the `locales` folder

It is now possible to keep the translations in the `locales`
folder and simply add the path of the screenshots
in the `manifest.webapp` file:
Ex:
```
"locales": {
    "en": {
      "screenshots": [
        "screenshots/en/screenshot01.png",
        "screenshots/en/screenshot02.png",
      ]
    },
    "fr": {
      "screenshots": [
        "screenshots/fr/screenshot01.png",
        "screenshots/fr/screenshot02.png",
      ]
    }
  }
```

- [x] See https://github.com/cozy/create-cozy-app/pull/1474 before

### CODE REVIEW

**Comment by Merkur39** [comment]
See https://github.com/cozy/create-cozy-app/pull/1474 before

**Review by Crash-- — APPROVED** [review]
It would be great to add a test for it ;)

**Comment by Merkur39** [comment]
> It would be great to add a test for it ;)

Ca sera l'objet de autre PR, ça génère beaucoup de changements (upgrade de Jest, snaps, ...) 👍

**Comment by Merkur39** [comment]
> It would be great to add a test for it ;)

En effet, je m'en occupe au plus vite! 👍

**Pull request merged**
